semgrep_rule_id,semgrep_rule_short,semgrep_category,semgrep_secret_type,semgrep_severity,semgrep_confidence,languages,example_payload,example_source,detection_regex
secrets.code.hardcoded-secret-key-spec-java.hardcoded-secret-key-spec-java,hardcoded-secret-key-spec-java,code,Static Encryption Key,WARNING,HIGH,java,"new SecretKeySpec(""0123456789abcdef0123456789abcdef"".getBytes(), ""AES"");",manual,
secrets.code.hardcoded-secret-key-spec-kt.hardcoded-secret-key-spec-kt,hardcoded-secret-key-spec-kt,code,Static Encryption Key,WARNING,HIGH,kotlin,"val key = SecretKeySpec(""0123456789abcdef0123456789abcdef"".toByteArray(), ""AES"")",manual,
secrets.generic.api-key.python-string.python-string,python-string,generic,Generic Secret,WARNING,HIGH,python,"api_key = ""abc123def456ghi789jkl012mno345pqr678""",manual,.*(?i:api[_.-]?key)
secrets.generic.api-key.string.string,string,generic,Generic Secret,WARNING,HIGH,regex,"api_key = ""abc123def456ghi789jkl012mno345pqr678""",manual,"(?<PROPERTY>(?i)(api[_\.-]?key)(?:[0-9a-z\-_\t\.]{0,20}))(?:[\s|']|[\s|""]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=|,|\()(?:'|\""|[ ]|=|\x60){0,5}(?<STRING>[a-zA-Z0-9_.+\!\/~$-]([a-zA-Z0-9_.+\!\/=~$-]|\\(?![ntr\""])){14,150}[a-zA-Z0-9_.+\!\/=~$-])"
secrets.generic.api-key.xml-dict.xml-dict,xml-dict,generic,Generic Secret,WARNING,HIGH,xml,<key>api_key</key><string>abc123def456ghi789jkl012mno345pqr678</string>,manual,.*(?i:api[_.-]?key)
secrets.generic.api-key.xml-string.xml-string,xml-string,generic,Generic Secret,WARNING,HIGH,xml,"<add key=""api_key"" value=""abc123def456ghi789jkl012mno345pqr678"" />",manual,(?i:api[_.-]?key)
secrets.generic.api-key.yaml-string.yaml-string,yaml-string,generic,Generic Secret,WARNING,HIGH,yaml,api_key: abc123def456ghi789jkl012mno345pqr678,manual,(?i:api[_.-]?key)
secrets.generic.client-key-and-secret.yaml-string.yaml-string,yaml-string,generic,Generic Secret,ERROR,HIGH,yaml,"client_id: abc123
client_secret: XyZ987AbC654DeF321GhI098JkL765MnO432PqR109",manual,(?i:client[_-]?(id|secret))
secrets.generic.password.xml-password.xml-password,xml-password,generic,Generic Secret,WARNING,HIGH,xml,<password>P@ssw0rd123!</password>,manual,(?i:password|pwd|passwd)
secrets.misc.generic-config-password.generic-config-password,generic-config-password,misc,Configuration Password,WARNING,HIGH,generic,"db.password = ""P@ssw0rd123!""",manual,
secrets.misc.generic_amqp_string.generic_amqp_string,generic_amqp_string,misc,Connection URI,WARNING,HIGH,regex,amqp://rabbituser:RabbitPass@rabbit.internal:5672/vhost,manual,"\bamqps?://(?<USERNAME>[\S]{3,50}):(?<REGEX>([\S]{3,50}))@[-.%\w\/:]+\b"
secrets.misc.generic_basic_auth_header.generic_basic_auth_header,generic_basic_auth_header,misc,Authorization Header,WARNING,LOW,regex,Basic kfIourfoqjr1Ke4QA==,regex,"\bBasic (?<REGEX>[A-Za-z0-9]{12,}(?:={1,2})?)"
secrets.misc.generic_ftp_string.generic_ftp_string,generic_ftp_string,misc,Connection URI,WARNING,HIGH,regex,ftp://deploy:FtpPass99@files.internal:21,manual,"\bs?ftp://(?<USERNAME>[\S]{3,50}):(?<REGEX>([\S]{3,50}))@[-.%\w\/:]+\b"
secrets.misc.generic_jwt.generic_jwt,generic_jwt,misc,JWT,WARNING,MEDIUM,regex,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c,manual,"(?<REGEX>\b(ey[A-Za-z0-9]{17,}\.ey[A-Za-z0-9\/\\_-]{17,}\.(?:[A-Za-z0-9\/\\_-]{10,}={0,2})?))(?:['|\""|\n|\r|\s|\x60|;]|$)"
secrets.misc.generic_mongodb_string.generic_mongodb_string,generic_mongodb_string,misc,Connection URI,WARNING,HIGH,regex,mongodb://appuser:LeakedPw2024@mongo.internal:27017/orders,manual,"\b(mongodb(\+srv)?://(?<USERNAME>[\S]{3,50}):(?<REGEX>([\S]{3,50}))@[-.%\w\/:]+)\b"
secrets.misc.generic_mssql_string.generic_mssql_string,generic_mssql_string,misc,Connection URI,WARNING,HIGH,regex,sqlserver://sa:S3cretPass@sql.internal:1433/master,manual,"\bmssql://(?<USERNAME>[\S]{3,50}):(?<REGEX>([\S]{3,50}))@[-.%\w\/:]+\b"
secrets.misc.generic_mysql_string.generic_mysql_string,generic_mysql_string,misc,Connection URI,WARNING,HIGH,regex,mysql://root:P@ssw0rd123@10.0.0.5:3306/appdb,manual,"\bmysql://(?<USERNAME>[\S]{3,50}):(?<REGEX>([\S]{3,50}))@[-.%\w\/:]+\b"
secrets.misc.generic_postgres_string.generic_postgres_string,generic_postgres_string,misc,Connection URI,WARNING,HIGH,regex,postgres://admin:hunter2@db.internal:5432/prod,manual,"\bpostgres(ql)?://(?<USERNAME>[\S]{3,50}):(?<REGEX>([\S]{3,50}))@[-.%\w\/:]+\b"
secrets.misc.generic_private_key_pgp.generic_private_key_pgp,generic_private_key_pgp,misc,Private Key,ERROR,HIGH,regex,"-----BEGIN PGP PRIVATE KEY BLOCK-----
Version: GnuPG v2
